name: build-windows
# build and test of tesseract on windows using vcpkg and cmake.
# vcpkg with -head does not work. https://github.com/microsoft/vcpkg/issues/16019
on:
  push:
  
jobs:
  build:
    runs-on: windows-2019
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     os: [windows-2019]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Resolve tesseract version
      run: |
        $Version = Get-Content -Path VERSION
        Add-Content -Path $env:GITHUB_ENV -Value "TESSERACT_VERISON=$Version"
        Write-Host "Tesseract Version: $Version"
                      
    - name: Visual Studio Setup
      shell: cmd
      run: |
            call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

    - name: Fetch & install vcpkg
      run: |
            git clone https://github.com/microsoft/vcpkg
            vcpkg/bootstrap-vcpkg.bat
            vcpkg/vcpkg integrate install

    - name: Fetch tesseract source  
      run: |
            git clone --branch $env:TESSERACT_VERISON "https://github.com/tesseract-ocr/tesseract"
            
    - name: Build leptonica
      run: |
            vcpkg/vcpkg install leptonica:x64-windows

    - name: Build tesseract  
      run: |
            Push-Location tesseract
            cmake . -B build -DCMAKE_BUILD_TYPE=Release -DSW_BUILD=OFF -DOPENMP_BUILD=OFF -DBUILD_TRAINING_TOOLS=OFF -DBUILD_SHARED_LIBS=ON "-DCMAKE_TOOLCHAIN_FILE=..\vcpkg\scripts\buildsystems\vcpkg.cmake"
            cmake --build build --config Release -j 3

    - name: Upload build artifact 
      uses: actions/upload-artifact@v2
      with:
        name: win-x64
        path: '${{ github.workspace }}\tesseract\build\bin\Release\'
